 services:
  - type: web
    name: assignment-portal-backend
    env: python
    plan: free # Or your desired plan
    region: oregon # Optional: Choose a region close to your users/db
    buildCommand: "pip install --no-cache-dir -r requirements.txt" # Use --no-cache-dir for cleaner builds
    startCommand: "uvicorn app.main:app --host 0.0.0.0 --port $PORT --forwarded-allow-ips='*'" # Allow forwarded headers
    healthCheckPath: /api/health # Add a health check endpoint
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: assignment-portal-db # Match the database name below
          property: connectionString
      - key: DATABASE_NAME # Pass the DB name if needed, or extract from URL
        value: assignment_portal # Match DB name below
      - key: JWT_SECRET_KEY
        generateValue: true # Let Render generate a secure secret
      - key: ALGORITHM
        value: HS256
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: 60
      - key: GOOGLE_CLIENT_ID
        sync: false # Set securely in Render's UI
      - key: GOOGLE_CLIENT_SECRET
        sync: false # Set securely in Render's UI
      # - key: BACKEND_URL # Set in UI if needed
      #   sync: false
      # - key: FRONTEND_URL # Set in UI if needed
      #   sync: false
      - key: PYTHON_VERSION # Optional: Specify Python version
        value: 3.11

databases:
  - name: assignment-portal-db
    databaseName: assignment_portal # The logical database name
    plan: free # Or your desired plan
    region: oregon # Optional: Keep DB close to the service
    ipAllowList: [] # Automatically allows Render IPs. Restrict further if necessary.

# Optional: Redirects/Rewrites (usually handled in FastAPI/Frontend)
# redirects:
#   - source: /old-path
#     destination: /new-path
#     type: permanent